# Generated by Django 5.2.8 on 2025-12-10 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionextrusion",
            name="nombre_machines_actives",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Nombre moyen de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="rendement_pourcentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="nombre_machines_actives",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Nombre moyen de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="nombre_moulinex",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Nombre de moulinex",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="taux_transformation_pourcentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="nombre_machines_actives",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Nombre moyen de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Taux de déchets (%)",
            ),
        ),
    ]
