# Generated by Django 4.2.7 on 2025-10-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sofemci', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
