# Generated by Django 6.0 on 2025-12-30 16:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rapportmensuel",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="rapportmensuel",
            name="genere_par",
        ),
        migrations.AlterModelOptions(
            name="alerte",
            options={
                "ordering": ["-date_creation", "priorite"],
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
            },
        ),
        migrations.AlterModelOptions(
            name="alerteia",
            options={
                "ordering": ["-date_creation", "niveau"],
                "verbose_name": "Alerte IA",
                "verbose_name_plural": "Alertes IA",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="equipe",
            options={
                "ordering": ["heure_debut"],
                "verbose_name": "Équipe",
                "verbose_name_plural": "Équipes",
            },
        ),
        migrations.AlterModelOptions(
            name="historiquemachine",
            options={
                "ordering": ["-date_evenement"],
                "verbose_name": "Historique machine",
                "verbose_name_plural": "Historiques machines",
            },
        ),
        migrations.AlterModelOptions(
            name="machine",
            options={
                "ordering": ["numero"],
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
            },
        ),
        migrations.AlterModelOptions(
            name="productionextrusion",
            options={
                "ordering": ["-date_production", "zone"],
                "verbose_name": "Production extrusion",
                "verbose_name_plural": "Productions extrusion",
            },
        ),
        migrations.AlterModelOptions(
            name="productionimprimerie",
            options={
                "ordering": ["-date_production"],
                "verbose_name": "Production imprimerie",
                "verbose_name_plural": "Productions imprimerie",
            },
        ),
        migrations.AlterModelOptions(
            name="productionrecyclage",
            options={
                "ordering": ["-date_production", "equipe"],
                "verbose_name": "Production recyclage",
                "verbose_name_plural": "Productions recyclage",
            },
        ),
        migrations.AlterModelOptions(
            name="productionsoudure",
            options={
                "ordering": ["-date_production"],
                "verbose_name": "Production soudure",
                "verbose_name_plural": "Productions soudure",
            },
        ),
        migrations.AlterModelOptions(
            name="zoneextrusion",
            options={
                "ordering": ["numero"],
                "verbose_name": "Zone d'extrusion",
                "verbose_name_plural": "Zones d'extrusion",
            },
        ),
        migrations.AlterUniqueTogether(
            name="alerteia",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="machine",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productionimprimerie",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productionrecyclage",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productionsoudure",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="equipe",
            name="description",
        ),
        migrations.RemoveField(
            model_name="historiquemachine",
            name="consommation_kwh",
        ),
        migrations.RemoveField(
            model_name="historiquemachine",
            name="cree_par",
        ),
        migrations.RemoveField(
            model_name="historiquemachine",
            name="duree_arret",
        ),
        migrations.RemoveField(
            model_name="historiquemachine",
            name="heures_fonctionnement",
        ),
        migrations.RemoveField(
            model_name="historiquemachine",
            name="pieces_remplacees",
        ),
        migrations.RemoveField(
            model_name="historiquemachine",
            name="temperature",
        ),
        migrations.AddField(
            model_name="alerte",
            name="delai_resolution",
            field=models.IntegerField(
                default=24, verbose_name="Délai de résolution (heures)"
            ),
        ),
        migrations.AddField(
            model_name="alerte",
            name="pieces_jointes",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="alertes/",
                verbose_name="Pièces jointes",
            ),
        ),
        migrations.AddField(
            model_name="alerte",
            name="priorite",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Priorité (1-5)",
            ),
        ),
        migrations.AddField(
            model_name="alerte",
            name="solution",
            field=models.TextField(
                blank=True, null=True, verbose_name="Solution apportée"
            ),
        ),
        migrations.AddField(
            model_name="alerteia",
            name="action_traitement",
            field=models.TextField(
                blank=True, null=True, verbose_name="Action de traitement"
            ),
        ),
        migrations.AddField(
            model_name="alerteia",
            name="recommandations",
            field=models.TextField(
                blank=True, default="", verbose_name="Recommandations IA"
            ),
        ),
        migrations.AddField(
            model_name="alerteia",
            name="variables_anormales",
            field=models.JSONField(
                default=dict,
                help_text="Données anormales détectées",
                verbose_name="Variables anormales",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="dernier_acces",
            field=models.DateTimeField(auto_now=True, verbose_name="Dernier accès"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="est_actif",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="matricule",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Matricule",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="service",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Service/Service"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="signature",
            field=models.ImageField(
                blank=True, null=True, upload_to="signatures/", verbose_name="Signature"
            ),
        ),
        migrations.AddField(
            model_name="equipe",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AddField(
            model_name="equipe",
            name="est_active",
            field=models.BooleanField(default=True, verbose_name="Équipe active"),
        ),
        migrations.AddField(
            model_name="equipe",
            name="nombre_membres",
            field=models.IntegerField(default=0, verbose_name="Nombre de membres"),
        ),
        migrations.AddField(
            model_name="equipe",
            name="observations",
            field=models.TextField(blank=True, null=True, verbose_name="Observations"),
        ),
        migrations.AddField(
            model_name="historiquemachine",
            name="duree_intervention",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Durée intervention (heures)",
            ),
        ),
        migrations.AddField(
            model_name="historiquemachine",
            name="observations",
            field=models.TextField(blank=True, null=True, verbose_name="Observations"),
        ),
        migrations.AddField(
            model_name="historiquemachine",
            name="pieces_utilisees",
            field=models.TextField(
                blank=True, null=True, verbose_name="Pièces utilisées"
            ),
        ),
        migrations.AddField(
            model_name="historiquemachine",
            name="signature_technicien",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="signatures_techniciens/",
                verbose_name="Signature technicien",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="est_nouvelle",
            field=models.BooleanField(
                default=True,
                help_text="Cochez si la machine est neuve (non usagée)",
                verbose_name="Machine neuve?",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="provenance",
            field=models.CharField(
                choices=[
                    ("LOCAL", "Local (Abidjan)"),
                    ("IMPORT_FRANCE", "Importé de France"),
                    ("IMPORT_CHINE", "Importé de Chine"),
                    ("IMPORT_ALLEMAGNE", "Importé d'Allemagne"),
                    ("USAGÉ_LOCAL", "Usagé (marché local)"),
                    ("USAGÉ_IMPORT", "Usagé (importé)"),
                    ("NEUF_LOCAL", "Neuf (fournisseur local)"),
                    ("NEUF_IMPORT", "Neuf (importé)"),
                    ("SOFEM_CI", "Fabrication SOFEM-CI"),
                    ("AUTRE", "Autre origine"),
                ],
                default="LOCAL",
                help_text="Origine de la machine",
                max_length=50,
                verbose_name="Provenance",
            ),
        ),
        migrations.AddField(
            model_name="zoneextrusion",
            name="capacite_max",
            field=models.PositiveBigIntegerField(
                default=100,
                help_text="Capacité maximale de la zone d'extrusion",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="zoneextrusion",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AddField(
            model_name="zoneextrusion",
            name="observations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observations techniques"
            ),
        ),
        migrations.AddField(
            model_name="zoneextrusion",
            name="pression_optimale",
            field=models.DecimalField(
                decimal_places=2,
                default=150.0,
                max_digits=5,
                verbose_name="Pression optimale (bar)",
            ),
        ),
        migrations.AddField(
            model_name="zoneextrusion",
            name="temperature_optimale",
            field=models.DecimalField(
                decimal_places=2,
                default=180.0,
                max_digits=5,
                verbose_name="Température optimale (°C)",
            ),
        ),
        migrations.AlterField(
            model_name="alerte",
            name="assigne_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertes_assignees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigné à",
            ),
        ),
        migrations.AlterField(
            model_name="alerte",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertes_creees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="alerte",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="alerte",
            name="date_resolution",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de résolution"
            ),
        ),
        migrations.AlterField(
            model_name="alerte",
            name="message",
            field=models.TextField(verbose_name="Message détaillé"),
        ),
        migrations.AlterField(
            model_name="alerte",
            name="section",
            field=models.CharField(
                choices=[
                    ("EXTRUSION", "Extrusion"),
                    ("IMPRIMERIE", "Imprimerie"),
                    ("SOUDURE", "Soudure"),
                    ("RECYCLAGE", "Recyclage"),
                    ("GENERAL", "Général"),
                    ("MAINTENANCE", "Maintenance"),
                    ("ADMIN", "Administration"),
                ],
                max_length=20,
                verbose_name="Section concernée",
            ),
        ),
        migrations.AlterField(
            model_name="alerte",
            name="statut",
            field=models.CharField(
                choices=[
                    ("NOUVELLE", "🆕 Nouvelle"),
                    ("EN_COURS", "🔄 En cours"),
                    ("RESOLUE", "✅ Résolue"),
                    ("ANNULEE", "❌ Annulée"),
                ],
                default="NOUVELLE",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="alerte",
            name="titre",
            field=models.CharField(max_length=200, verbose_name="Titre de l'alerte"),
        ),
        migrations.AlterField(
            model_name="alerte",
            name="type_alerte",
            field=models.CharField(
                choices=[
                    ("PRODUCTION", "Production"),
                    ("QUALITE", "Qualité"),
                    ("SECURITE", "Sécurité"),
                    ("MAINTENANCE", "Maintenance"),
                    ("STOCK", "Stock"),
                    ("PERSONNEL", "Personnel"),
                    ("SYSTEME", "Système"),
                    ("AUTRE", "Autre"),
                ],
                max_length=20,
                verbose_name="Type d'alerte",
            ),
        ),
        migrations.AlterField(
            model_name="alerteia",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="alerteia",
            name="date_traitement",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de traitement"
            ),
        ),
        migrations.AlterField(
            model_name="alerteia",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertes_ia",
                to="sofemci.machine",
                verbose_name="Machine",
            ),
        ),
        migrations.AlterField(
            model_name="alerteia",
            name="message",
            field=models.TextField(verbose_name="Message IA"),
        ),
        migrations.AlterField(
            model_name="alerteia",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("CRITIQUE", "🔴 Critique"),
                    ("HAUTE", "🟠 Haute"),
                    ("MOYENNE", "🟡 Moyenne"),
                    ("BASSE", "🟢 Basse"),
                    ("INFORMATION", "🔵 Information"),
                ],
                max_length=20,
                verbose_name="Niveau d'alerte",
            ),
        ),
        migrations.AlterField(
            model_name="alerteia",
            name="probabilite_panne",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Probabilité de panne (%)",
            ),
        ),
        migrations.AlterField(
            model_name="alerteia",
            name="statut",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("TRAITEE", "Traitée"),
                    ("IGNOREE", "Ignorée"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="alerteia",
            name="titre",
            field=models.CharField(max_length=200, verbose_name="Titre de l'alerte"),
        ),
        migrations.AlterField(
            model_name="alerteia",
            name="traite_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Traité par",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_embauche",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'embauche"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("SUPERVISEUR", "Superviseur"),
                    ("CHEF_ZONE", "Chef de Zone"),
                    ("OPERATEUR", "Opérateur"),
                    ("TECHNICIEN", "Technicien"),
                    ("QUALITE", "Contrôle Qualité"),
                    ("LOGISTIQUE", "Logistique"),
                    ("COMPTABLE", "Comptable"),
                    ("RH", "Ressources Humaines"),
                    ("VISITEUR", "Visiteur"),
                ],
                default="OPERATEUR",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format: '+2250102030405' ou '0102030405'",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="chef_equipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipes_dirigees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Chef d'équipe",
            ),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="heure_debut",
            field=models.TimeField(verbose_name="Heure de début"),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="heure_fin",
            field=models.TimeField(verbose_name="Heure de fin"),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="nom",
            field=models.CharField(
                choices=[
                    ("MATIN", "Équipe Matin (06h-14h)"),
                    ("SOIR", "Équipe Soir (14h-22h)"),
                    ("NUIT", "Équipe Nuit (22h-06h)"),
                    ("JOUR", "Équipe Jour (08h-17h)"),
                    ("SPECIALE", "Équipe Spéciale"),
                ],
                max_length=20,
                verbose_name="Nom de l'équipe",
            ),
        ),
        migrations.AlterField(
            model_name="historiquemachine",
            name="cout_intervention",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Coût intervention (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="historiquemachine",
            name="date_evenement",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de l'événement"
            ),
        ),
        migrations.AlterField(
            model_name="historiquemachine",
            name="description",
            field=models.TextField(verbose_name="Description détaillée"),
        ),
        migrations.AlterField(
            model_name="historiquemachine",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historique",
                to="sofemci.machine",
                verbose_name="Machine",
            ),
        ),
        migrations.AlterField(
            model_name="historiquemachine",
            name="technicien",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Technicien",
            ),
        ),
        migrations.AlterField(
            model_name="historiquemachine",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("MAINTENANCE", "Maintenance"),
                    ("PANNE", "Panne"),
                    ("REPARATION", "Réparation"),
                    ("CONTROLE", "Contrôle technique"),
                    ("CALIBRAGE", "Calibrage"),
                    ("NETTOYAGE", "Nettoyage"),
                    ("AMELIORATION", "Amélioration"),
                    ("REMIS_EN_SERVICE", "Remis en service"),
                    ("HORS_SERVICE", "Mis hors service"),
                ],
                max_length=20,
                verbose_name="Type d'événement",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="capacite_horaire",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Capacité horaire (kg/h)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="consommation_electrique_kwh",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Consommation électrique (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="consommation_electrique_nominale",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Consommation nominale (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="date_derniere_analyse_ia",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date dernière analyse IA"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="date_derniere_panne",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date dernière panne"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="date_installation",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date d'installation"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="derniere_maintenance",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date dernière maintenance"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="duree_moyenne_reparation",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Durée moyenne réparation (heures)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="etat",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "🟢 Active"),
                    ("INACTIVE", "🔴 Inactive"),
                    ("MAINTENANCE", "🟡 En maintenance"),
                    ("PANNE", "🔴 En panne"),
                    ("HORS_SERVICE", "⚫ Hors service"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="État",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="frequence_maintenance_jours",
            field=models.IntegerField(
                default=30,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Fréquence maintenance (jours)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="heures_fonctionnement_totales",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Heures fonctionnement totales",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="nombre_pannes_1_dernier_mois",
            field=models.IntegerField(
                default=0, verbose_name="Pannes (1 dernier mois)"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="nombre_pannes_6_derniers_mois",
            field=models.IntegerField(
                default=0, verbose_name="Pannes (6 derniers mois)"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="nombre_pannes_totales",
            field=models.IntegerField(default=0, verbose_name="Nombre total de pannes"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="numero",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Numéro de machine"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="observations",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observations techniques"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="probabilite_panne_30_jours",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Probabilité panne (30 jours, %)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="probabilite_panne_7_jours",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Probabilité panne (7 jours, %)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="score_sante_global",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Score santé global (%)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="section",
            field=models.CharField(
                choices=[
                    ("EXTRUSION", "Extrusion"),
                    ("IMPRIMERIE", "Imprimerie"),
                    ("SOUDURE", "Soudure"),
                    ("RECYCLAGE", "Recyclage"),
                    ("MAINTENANCE", "Maintenance"),
                    ("STOCKAGE", "Stockage"),
                ],
                max_length=50,
                verbose_name="Section",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="temperature_actuelle",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Température actuelle (°C)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="temperature_max_autorisee",
            field=models.DecimalField(
                decimal_places=2,
                default=200.0,
                max_digits=5,
                verbose_name="Température max autorisée (°C)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="temperature_nominale",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Température nominale (°C)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="type_anomalie",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Type d'anomalie"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="type_machine",
            field=models.CharField(
                choices=[
                    ("EXTRUDEUSE", "Extrudeuse"),
                    ("IMPRIMANTE", "Machine d'impression"),
                    ("SOUDEUSE", "Soudeuse"),
                    ("MOULINEX", "Moulinex (Recyclage)"),
                    ("BROYEUSE", "Broyeuse"),
                    ("TRANSFORMATEUR", "Transformateur"),
                    ("COMPACTEUR", "Compacteur"),
                    ("CONVOYEUR", "Convoyeur"),
                    ("MELANGEUR", "Mélangeur"),
                    ("AUTRE", "Autre"),
                ],
                max_length=50,
                verbose_name="Type de machine",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="zone_extrusion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sofemci.zoneextrusion",
                verbose_name="Zone d'extrusion (si applicable)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="chef_zone",
            field=models.CharField(max_length=100, verbose_name="Chef de zone"),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productions_extrusion_creees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="date_modification",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="date_production",
            field=models.DateField(verbose_name="Date de production"),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="dechets_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="equipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sofemci.equipe",
                verbose_name="Équipe",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="heure_debut",
            field=models.TimeField(verbose_name="Heure de début"),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="heure_fin",
            field=models.TimeField(verbose_name="Heure de fin"),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="matiere_premiere_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Matière première (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="nombre_bobines_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de bobines (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="nombre_machines_actives",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="nombre_machinistes",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machinistes",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="observations",
            field=models.TextField(blank=True, null=True, verbose_name="Observations"),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="production_finis_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production finis (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="production_par_machine",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Production par machine (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="production_semi_finis_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production semi-finis (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="rendement_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=5,
                verbose_name="Rendement matière (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="valide",
            field=models.BooleanField(default=False, verbose_name="Validé"),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sofemci.zoneextrusion",
                verbose_name="Zone d'extrusion",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productions_imprimerie_creees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="date_modification",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="date_production",
            field=models.DateField(verbose_name="Date de production"),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="dechets_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="heure_debut",
            field=models.TimeField(verbose_name="Heure de début"),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="heure_fin",
            field=models.TimeField(verbose_name="Heure de fin"),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="nombre_machines_actives",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="observations",
            field=models.TextField(blank=True, null=True, verbose_name="Observations"),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="production_bobines_finies_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bobines finies (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="production_bobines_semi_finies_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bobines semi-finies (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="valide",
            field=models.BooleanField(default=False, verbose_name="Validé"),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productions_recyclage_creees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="date_modification",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="date_production",
            field=models.DateField(verbose_name="Date de production"),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="equipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sofemci.equipe",
                verbose_name="Équipe",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="nombre_moulinex",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de moulinex",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="observations",
            field=models.TextField(blank=True, null=True, verbose_name="Observations"),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="production_bache_noir_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Bâche noire produite (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="production_broyage_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production broyage (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="production_par_moulinex",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Production par moulinex (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="taux_transformation_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=5,
                verbose_name="Taux de transformation (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="valide",
            field=models.BooleanField(default=False, verbose_name="Validé"),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="cree_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productions_soudure_creees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="date_creation",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="date_modification",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="date_production",
            field=models.DateField(verbose_name="Date de production"),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="dechets_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="heure_debut",
            field=models.TimeField(verbose_name="Heure de début"),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="heure_fin",
            field=models.TimeField(verbose_name="Heure de fin"),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="nombre_machines_actives",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="observations",
            field=models.TextField(blank=True, null=True, verbose_name="Observations"),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_batta_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production BATTA (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_bobines_finies_kg",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bobines finies (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_bretelles_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bretelles (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_rema_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production REMA-Plastique (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_sac_emballage_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production sac d'emballage imprimé (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="total_production_specifique_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=10,
                verbose_name="Production spécifique totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="valide",
            field=models.BooleanField(default=False, verbose_name="Validé"),
        ),
        migrations.AlterField(
            model_name="zoneextrusion",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Zone active"),
        ),
        migrations.AlterField(
            model_name="zoneextrusion",
            name="chef_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="zones_dirigees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Chef de zone",
            ),
        ),
        migrations.AlterField(
            model_name="zoneextrusion",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="Nom de la zone"),
        ),
        migrations.AlterField(
            model_name="zoneextrusion",
            name="nombre_machines_max",
            field=models.IntegerField(
                default=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Nombre maximum de machines",
            ),
        ),
        migrations.AlterField(
            model_name="zoneextrusion",
            name="numero",
            field=models.IntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Numéro de zone",
            ),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(
                fields=["statut", "section"], name="sofemci_ale_statut_81fc48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(
                fields=["date_creation"], name="sofemci_ale_date_cr_41a91c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerteia",
            index=models.Index(
                fields=["machine", "statut"], name="sofemci_ale_machine_b267e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerteia",
            index=models.Index(
                fields=["date_creation"], name="sofemci_ale_date_cr_b3de6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historiquemachine",
            index=models.Index(
                fields=["machine", "date_evenement"],
                name="sofemci_his_machine_ed8864_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(
                fields=["section", "etat"], name="sofemci_mac_section_383199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(fields=["numero"], name="sofemci_mac_numero_e08442_idx"),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(
                fields=["type_machine"], name="sofemci_mac_type_ma_afe02f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionextrusion",
            index=models.Index(
                fields=["date_production", "zone"],
                name="sofemci_pro_date_pr_06d4a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionextrusion",
            index=models.Index(fields=["valide"], name="sofemci_pro_valide_7a4664_idx"),
        ),
        migrations.AddIndex(
            model_name="productionimprimerie",
            index=models.Index(
                fields=["date_production"], name="sofemci_pro_date_pr_a0b081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionimprimerie",
            index=models.Index(fields=["valide"], name="sofemci_pro_valide_133d45_idx"),
        ),
        migrations.AddIndex(
            model_name="productionrecyclage",
            index=models.Index(
                fields=["date_production", "equipe"],
                name="sofemci_pro_date_pr_d61d49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionrecyclage",
            index=models.Index(fields=["valide"], name="sofemci_pro_valide_67c84f_idx"),
        ),
        migrations.AddIndex(
            model_name="productionsoudure",
            index=models.Index(
                fields=["date_production"], name="sofemci_pro_date_pr_548dd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionsoudure",
            index=models.Index(fields=["valide"], name="sofemci_pro_valide_19dd92_idx"),
        ),
        migrations.DeleteModel(
            name="RapportMensuel",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="action_recommandee",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="capacite_horaire",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="commentaire_traitement",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="confiance_prediction",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="date_installation",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="delai_estime_jours",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="derniere_maintenance",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="donnees_analyse",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="etat",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="modele_ia_version",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="observations",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="priorite",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="section",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="type_machine",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="zone_extrusion",
        ),
    ]
