# Generated by Django 5.2.8 on 2025-12-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionextrusion",
            name="rendement_pourcentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
