# Generated by Django 4.2.7 on 2025-10-06 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sofemci', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['section', 'numero'], 'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
        migrations.AddField(
            model_name='machine',
            name='anomalie_detectee',
            field=models.BooleanField(default=False, verbose_name='Anomalie détectée'),
        ),
        migrations.AddField(
            model_name='machine',
            name='consommation_electrique_kwh',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Consommation moyenne par heure', max_digits=10, verbose_name='Consommation électrique actuelle (kWh)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='consommation_electrique_nominale',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Consommation normale à pleine charge', max_digits=10, verbose_name='Consommation nominale (kWh)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='date_derniere_analyse_ia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière analyse IA'),
        ),
        migrations.AddField(
            model_name='machine',
            name='date_derniere_panne',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date dernière panne'),
        ),
        migrations.AddField(
            model_name='machine',
            name='derniere_mise_a_jour_donnees',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour données'),
        ),
        migrations.AddField(
            model_name='machine',
            name='duree_moyenne_reparation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Durée moyenne réparation (heures)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='frequence_maintenance_jours',
            field=models.IntegerField(default=90, help_text='Intervalle recommandé entre maintenances', verbose_name='Fréquence maintenance (jours)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='heures_depuis_derniere_maintenance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Heures depuis dernière maintenance'),
        ),
        migrations.AddField(
            model_name='machine',
            name='heures_fonctionnement_totales',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Nombre total d'heures depuis installation", max_digits=10, verbose_name='Heures de fonctionnement totales'),
        ),
        migrations.AddField(
            model_name='machine',
            name='nombre_pannes_1_dernier_mois',
            field=models.IntegerField(default=0, verbose_name='Pannes - dernier mois'),
        ),
        migrations.AddField(
            model_name='machine',
            name='nombre_pannes_6_derniers_mois',
            field=models.IntegerField(default=0, verbose_name='Pannes - 6 derniers mois'),
        ),
        migrations.AddField(
            model_name='machine',
            name='nombre_pannes_totales',
            field=models.IntegerField(default=0, verbose_name='Nombre de pannes totales'),
        ),
        migrations.AddField(
            model_name='machine',
            name='probabilite_panne_30_jours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Probabilité panne 30 jours (%)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='probabilite_panne_7_jours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Risque de panne dans les 7 prochains jours', max_digits=5, verbose_name='Probabilité panne 7 jours (%)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='prochaine_maintenance_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine maintenance prévue'),
        ),
        migrations.AddField(
            model_name='machine',
            name='score_sante_global',
            field=models.DecimalField(decimal_places=2, default=100, help_text="Score calculé par l'IA (0-100)", max_digits=5, verbose_name='Score santé global (%)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='temperature_actuelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Température actuelle (°C)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='temperature_max_autorisee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Température max autorisée (°C)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='temperature_nominale',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Température normale de fonctionnement', max_digits=5, verbose_name='Température nominale (°C)'),
        ),
        migrations.AddField(
            model_name='machine',
            name='type_anomalie',
            field=models.CharField(blank=True, help_text='Ex: Surchauffe, Surconsommation, Vibrations', max_length=100, verbose_name="Type d'anomalie"),
        ),
        migrations.CreateModel(
            name='HistoriqueMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evenement', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_evenement', models.CharField(choices=[('maintenance', 'Maintenance'), ('panne', 'Panne'), ('reparation', 'Réparation'), ('mesure', 'Mesure'), ('alerte', 'Alerte')], max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('consommation_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('heures_fonctionnement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('duree_arret', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Durée arrêt (heures)')),
                ('cout_intervention', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût (FCFA)')),
                ('technicien', models.CharField(blank=True, max_length=100)),
                ('pieces_remplacees', models.TextField(blank=True, help_text='Liste des pièces')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='sofemci.machine')),
            ],
            options={
                'verbose_name': 'Historique Machine',
                'verbose_name_plural': 'Historiques Machines',
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='AlerteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('attention', 'Attention'), ('urgent', 'Urgent'), ('critique', 'Critique')], max_length=20)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('vue', 'Vue'), ('en_traitement', 'En traitement'), ('resolue', 'Résolue'), ('ignoree', 'Ignorée')], default='nouvelle', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('probabilite_panne', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Probabilité panne (%)')),
                ('delai_estime_jours', models.IntegerField(blank=True, null=True, verbose_name='Délai estimé (jours)')),
                ('confiance_prediction', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Confiance prédiction (%)')),
                ('action_recommandee', models.TextField(blank=True, verbose_name='Action recommandée')),
                ('priorite', models.IntegerField(default=0, verbose_name='Priorité (0-10)')),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_traitement', models.TextField(blank=True)),
                ('modele_ia_version', models.CharField(default='v1.0', max_length=50)),
                ('donnees_analyse', models.JSONField(blank=True, default=dict, verbose_name="Données d'analyse JSON")),
                ('numero', models.CharField(max_length=10)),
                ('type_machine', models.CharField(choices=[('extrudeuse', 'Extrudeuse'), ('refroidisseur', 'Refroidisseur'), ('enrouleur', 'Enrouleur'), ('imprimante', 'Imprimante'), ('soudeuse', 'Soudeuse'), ('moulinex', 'Moulinex')], max_length=20)),
                ('section', models.CharField(choices=[('extrusion', 'Extrusion'), ('imprimerie', 'Imprimerie'), ('soudure', 'Soudure'), ('recyclage', 'Recyclage')], max_length=20)),
                ('etat', models.CharField(choices=[('actif', 'Active'), ('maintenance', 'Maintenance'), ('arret', 'Arrêtée'), ('panne', 'En Panne')], default='actif', max_length=15)),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('derniere_maintenance', models.DateField(blank=True, null=True)),
                ('capacite_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observations', models.TextField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_ia', to='sofemci.machine')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_ia_traitees', to=settings.AUTH_USER_MODEL)),
                ('zone_extrusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sofemci.zoneextrusion')),
            ],
            options={
                'ordering': ['section', 'numero'],
                'unique_together': {('numero', 'section')},
            },
        ),
    ]
