# Generated by Django 6.0 on 2026-01-08 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0002_alter_rapportmensuel_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionrecyclage",
            name="dechets_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AddField(
            model_name="productionrecyclage",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
    ]
