# Generated by Django 5.2.8 on 2025-12-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0002_alter_productionextrusion_nombre_machines_actives_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionextrusion",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
