# Generated by Django 4.2.7 on 2025-12-26 10:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0003_alter_machine_options_machine_anomalie_detectee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionsoudure",
            name="production_sac_emballage_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Production SAC D'EMBALLAGE IMPRIMÉ (kg)",
            ),
        ),
    ]
