# Generated by Django 4.2.7 on 2025-10-07 16:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofemci', '0003_alter_machine_options_machine_anomalie_detectee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsoudure',
            name='production_sac_emballage_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Production SAC D'EMBALLAGE IMPRIMÉ (kg)"),
        ),
        migrations.AlterField(
            model_name='productionsoudure',
            name='taux_dechet_pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de déchets (%)'),
        ),
        migrations.AlterField(
            model_name='productionsoudure',
            name='total_production_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total production globale'),
        ),
        migrations.AlterField(
            model_name='productionsoudure',
            name='total_production_specifique_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total production spécifique (Bretelle+Rema+Batta+Sac)'),
        ),
    ]
