# Generated by Django 6.0 on 2026-01-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0004_alter_historiquemachine_cout_intervention_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productionextrusion",
            old_name="dechets_kg",
            new_name="dechets",
        ),
        migrations.RenameField(
            model_name="productionimprimerie",
            old_name="dechets_kg",
            new_name="dechets",
        ),
        migrations.RenameField(
            model_name="productionrecyclage",
            old_name="dechets_kg",
            new_name="dechets",
        ),
        migrations.RenameField(
            model_name="productionsoudure",
            old_name="dechets_kg",
            new_name="dechets",
        ),
    ]
