# Generated by Django 4.2.7 on 2025-10-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofemci', '0004_productionsoudure_production_sac_emballage_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='annee_fabrication',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de fabrication'),
        ),
        migrations.AddField(
            model_name='machine',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='machine',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de série'),
        ),
        migrations.AddField(
            model_name='machine',
            name='pays_origine',
            field=models.CharField(blank=True, max_length=50, verbose_name="Pays d'origine"),
        ),
        migrations.AddField(
            model_name='machine',
            name='provenance_machine',
            field=models.CharField(choices=[('achat_neuf', 'Achat Neuf'), ('achat_occasion', 'Achat Occasion'), ('location', 'Location'), ('leasing', 'Leasing'), ('don', 'Don'), ('autre', 'Autre')], default='achat_neuf', max_length=20, verbose_name='Provenance de la machine'),
        ),
    ]
