# Generated by Django 6.0 on 2026-01-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0005_rename_dechets_kg_productionextrusion_dechets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="nom",
            field=models.CharField(
                choices=[
                    ("MATIN", "Équipe Matin (06h-14h)"),
                    ("SOIR", "Équipe Soir (14h-22h)"),
                    ("NUIT", "Équipe Nuit (22h-06h)"),
                ],
                max_length=20,
                verbose_name="Nom de l'équipe",
            ),
        ),
    ]
