# Generated by Django 4.2.7 on 2025-10-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sofemci', '0005_machine_annee_fabrication_machine_fournisseur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='annee_fabrication',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='pays_origine',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='provenance_machine',
        ),
    ]
