# Generated by Django 6.0 on 2026-01-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sofemci", "0006_alter_equipe_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="matricule",
            field=models.CharField(
                blank=True,
                help_text="Généré automatiquement si vide. Format: SOF-YYYY-NNNN",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Matricule",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("SUPERVISEUR", "Superviseur"),
                    ("CHEF_EXT1", "Chef de Zone1"),
                    ("CHEF_EXT2", "Chef de Zone2"),
                    ("CHEF_EXT3", "Chef de Zone3"),
                    ("CHEF_EXT4", "Chef de Zone4"),
                    ("CHEF_EXT5", "Chef de Zone5"),
                    ("CHEF_RECYCL", "Chef RECYCLAGE"),
                    ("CHEF_IMPRIM", "Chef IMPRIMERIE"),
                    ("CHEF_SOUD", "Chef SOUDURE"),
                    ("VISITEUR", "Visiteur"),
                    ("DIRECTION", "Direction"),
                ],
                default="CHEF_EXT1",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="nom",
            field=models.CharField(
                choices=[
                    ("MATIN", "Équipe Matin (06h00-14h00)"),
                    ("SOIR", "Équipe Soir (14h00-22h00)"),
                    ("NUIT", "Équipe Nuit (22h00-06h00)"),
                ],
                max_length=20,
                verbose_name="Nom de l'équipe",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["matricule"], name="sofemci_cus_matricu_9f3a32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["role"], name="sofemci_cus_role_35be31_idx"),
        ),
    ]
