# Generated by Django 4.2.7 on 2025-10-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofemci', '0006_remove_machine_annee_fabrication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='est_nouvelle',
            field=models.BooleanField(default=True, help_text="Indique si la machine était neuve lors de l'installation", verbose_name='Machine neuve'),
        ),
        migrations.AddField(
            model_name='machine',
            name='provenance',
            field=models.CharField(choices=[('chine', 'Chine'), ('allemagne', 'Allemagne'), ('italie', 'Italie'), ('france', 'France'), ('usa', 'États-Unis'), ('japon', 'Japon'), ('autre', 'Autre')], default='autre', help_text="Pays d'origine de la machine", max_length=20, verbose_name='Provenance'),
        ),
    ]
