# Generated by Django 6.0 on 2026-01-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0006_alter_equipe_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("SUPERVISEUR", "Superviseur"),
                    ("CHEF_EXT1", "Chef de Zone1"),
                    ("CHEF_EXT2", "Chef de Zone2"),
                    ("CHEF_EXT3", "Chef de Zone3"),
                    ("CHEF_EXT4", "Chef de Zone4"),
                    ("CHEF_EXT5", "Chef de Zone5"),
                    ("CHEF_RECYCL", "Chef RECYCLAGE"),
                    ("CHEF_IMPRIM", "Chef IMPRIMERIE"),
                    ("CHEF_SOUD", "Chef SOUDURE"),
                    ("VISITEUR", "Visiteur"),
                    ("DIRECTION", "Direction"),
                ],
                default="OPERATEUR",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
