# Generated by Django 6.0 on 2026-01-17 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0007_alter_customuser_matricule_alter_customuser_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerteia",
            name="probabilite_panne",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Probabilité de panne (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historiquemachine",
            name="cout_intervention",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Coût intervention (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="historiquemachine",
            name="duree_intervention",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Durée intervention (heures)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="capacite_horaire",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Capacité horaire (kg/h)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="consommation_electrique_kwh",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Consommation électrique (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="consommation_electrique_nominale",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Consommation nominale (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="duree_moyenne_reparation",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Durée moyenne réparation (heures)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="heures_depuis_derniere_maintenance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Heures depuis dernière maintenance",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="heures_fonctionnement_totales",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Heures fonctionnement totales",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="probabilite_panne_30_jours",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Probabilité panne (30 jours, %)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="probabilite_panne_7_jours",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Probabilité panne (7 jours, %)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="temperature_actuelle",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Température actuelle (°C)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="temperature_nominale",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Température nominale (°C)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="dechets",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="matiere_premiere_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Matière première (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="nombre_bobines_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de bobines (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="nombre_machines_actives",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="nombre_machinistes",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machinistes",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="production_finis_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production finis (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="production_par_machine",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production par machine (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="production_semi_finis_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production semi-finis (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="rendement_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Rendement matière (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="dechets",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="nombre_machines_actives",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="production_bobines_finies_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bobines finies (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="production_bobines_semi_finies_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bobines semi-finies (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="dechets",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="nombre_moulinex",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de moulinex",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="production_bache_noir_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Bâche noire produite (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="production_broyage_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production broyage (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="production_par_moulinex",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production par moulinex (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="taux_transformation_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Taux de transformation (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="dechets",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="nombre_machines_actives",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_batta_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production BATTA (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_bobines_finies_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bobines finies (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_bretelles_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bretelles (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_rema_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production REMA-Plastique (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_sac_emballage_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production sac d'emballage imprimé (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="total_production_specifique_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production spécifique totale (kg)",
            ),
        ),
    ]
