# Generated by Django 4.2.7 on 2025-10-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0007_machine_est_nouvelle_machine_provenance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RapportMensuel",
        ),
    ]
