# Generated by Django 5.2.8 on 2025-11-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0008_delete_rapportmensuel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alerteia",
            options={
                "ordering": ["-date_creation"],
                "verbose_name": "Alerte IA",
                "verbose_name_plural": "Alertes IA",
            },
        ),
        migrations.AlterUniqueTogether(
            name="alerteia",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="capacite_horaire",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="date_installation",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="derniere_maintenance",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="etat",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="observations",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="section",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="type_machine",
        ),
        migrations.RemoveField(
            model_name="alerteia",
            name="zone_extrusion",
        ),
    ]
