# Generated by Django 6.0 on 2026-01-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sofemci", "0008_alter_alerteia_probabilite_panne_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alerte",
            new_name="alerte_statut_section_idx",
            old_name="sofemci_ale_statut_81fc48_idx",
        ),
        migrations.RenameIndex(
            model_name="alerte",
            new_name="alerte_date_creation_idx",
            old_name="sofemci_ale_date_cr_41a91c_idx",
        ),
        migrations.RenameIndex(
            model_name="alerteia",
            new_name="alerte_ia_machine_statut_idx",
            old_name="sofemci_ale_machine_b267e0_idx",
        ),
        migrations.RenameIndex(
            model_name="alerteia",
            new_name="alerte_ia_date_creation_idx",
            old_name="sofemci_ale_date_cr_b3de6a_idx",
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="customuser_matricule_idx",
            old_name="sofemci_cus_matricu_9f3a32_idx",
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="customuser_role_idx",
            old_name="sofemci_cus_role_35be31_idx",
        ),
        migrations.RenameIndex(
            model_name="historiquemachine",
            new_name="historique_machine_date_idx",
            old_name="sofemci_his_machine_ed8864_idx",
        ),
        migrations.RenameIndex(
            model_name="machine",
            new_name="machine_section_etat_idx",
            old_name="sofemci_mac_section_383199_idx",
        ),
        migrations.RenameIndex(
            model_name="machine",
            new_name="machine_numero_idx",
            old_name="sofemci_mac_numero_e08442_idx",
        ),
        migrations.RenameIndex(
            model_name="machine",
            new_name="machine_type_idx",
            old_name="sofemci_mac_type_ma_afe02f_idx",
        ),
        migrations.RenameIndex(
            model_name="productionextrusion",
            new_name="prod_extrusion_date_zone_idx",
            old_name="sofemci_pro_date_pr_06d4a9_idx",
        ),
        migrations.RenameIndex(
            model_name="productionextrusion",
            new_name="prod_extrusion_valide_idx",
            old_name="sofemci_pro_valide_7a4664_idx",
        ),
        migrations.RenameIndex(
            model_name="productionimprimerie",
            new_name="prod_imprimerie_date_idx",
            old_name="sofemci_pro_date_pr_a0b081_idx",
        ),
        migrations.RenameIndex(
            model_name="productionimprimerie",
            new_name="prod_imprimerie_valide_idx",
            old_name="sofemci_pro_valide_133d45_idx",
        ),
        migrations.RenameIndex(
            model_name="productionrecyclage",
            new_name="prod_recyclage_date_equipe_idx",
            old_name="sofemci_pro_date_pr_d61d49_idx",
        ),
        migrations.RenameIndex(
            model_name="productionrecyclage",
            new_name="prod_recyclage_valide_idx",
            old_name="sofemci_pro_valide_67c84f_idx",
        ),
        migrations.RenameIndex(
            model_name="productionsoudure",
            new_name="prod_soudure_date_idx",
            old_name="sofemci_pro_date_pr_548dd5_idx",
        ),
        migrations.RenameIndex(
            model_name="productionsoudure",
            new_name="prod_soudure_valide_idx",
            old_name="sofemci_pro_valide_19dd92_idx",
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(fields=["cree_par"], name="alerte_cree_par_idx"),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(fields=["assigne_a"], name="alerte_assigne_a_idx"),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(fields=["priorite"], name="alerte_priorite_idx"),
        ),
        migrations.AddIndex(
            model_name="alerteia",
            index=models.Index(fields=["niveau"], name="alerte_ia_niveau_idx"),
        ),
        migrations.AddIndex(
            model_name="alerteia",
            index=models.Index(fields=["traite_par"], name="alerte_ia_traite_par_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["last_name", "first_name"], name="customuser_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipe",
            index=models.Index(fields=["nom"], name="equipe_nom_idx"),
        ),
        migrations.AddIndex(
            model_name="equipe",
            index=models.Index(fields=["est_active"], name="equipe_active_idx"),
        ),
        migrations.AddIndex(
            model_name="historiquemachine",
            index=models.Index(fields=["type_evenement"], name="historique_type_idx"),
        ),
        migrations.AddIndex(
            model_name="historiquemachine",
            index=models.Index(fields=["technicien"], name="historique_technicien_idx"),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(fields=["zone_extrusion"], name="machine_zone_idx"),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(fields=["etat"], name="machine_etat_idx"),
        ),
        migrations.AddIndex(
            model_name="productionextrusion",
            index=models.Index(
                fields=["date_creation"], name="prod_extrusion_creation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionextrusion",
            index=models.Index(fields=["equipe"], name="prod_extrusion_equipe_idx"),
        ),
        migrations.AddIndex(
            model_name="productionimprimerie",
            index=models.Index(
                fields=["date_creation"], name="prod_imprimerie_creation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionrecyclage",
            index=models.Index(
                fields=["date_creation"], name="prod_recyclage_creation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionsoudure",
            index=models.Index(
                fields=["date_creation"], name="prod_soudure_creation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zoneextrusion",
            index=models.Index(fields=["numero"], name="zone_numero_idx"),
        ),
        migrations.AddIndex(
            model_name="zoneextrusion",
            index=models.Index(fields=["active"], name="zone_active_idx"),
        ),
        migrations.AddIndex(
            model_name="zoneextrusion",
            index=models.Index(fields=["chef_zone"], name="zone_chef_idx"),
        ),
    ]
