# Generated by Django 5.2.8 on 2025-11-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sofemci", "0009_alter_alerteia_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productionextrusion",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productionimprimerie",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productionrecyclage",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productionsoudure",
            unique_together=set(),
        ),
    ]
