# Generated by Django 6.0 on 2026-01-17 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sofemci", "0010_remove_alerte_alerte_cree_par_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alerte",
            new_name="alerte_statut_section_idx",
            old_name="sofemci_ale_statut_81fc48_idx",
        ),
        migrations.RenameIndex(
            model_name="alerte",
            new_name="alerte_date_creation_idx",
            old_name="sofemci_ale_date_cr_41a91c_idx",
        ),
        migrations.RenameIndex(
            model_name="alerteia",
            new_name="alerte_ia_machine_statut_idx",
            old_name="sofemci_ale_machine_b267e0_idx",
        ),
        migrations.RenameIndex(
            model_name="alerteia",
            new_name="alerte_ia_date_creation_idx",
            old_name="sofemci_ale_date_cr_b3de6a_idx",
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="customuser_matricule_idx",
            old_name="sofemci_cus_matricu_9f3a32_idx",
        ),
        migrations.RenameIndex(
            model_name="customuser",
            new_name="customuser_role_idx",
            old_name="sofemci_cus_role_35be31_idx",
        ),
        migrations.RenameIndex(
            model_name="historiquemachine",
            new_name="historique_machine_date_idx",
            old_name="sofemci_his_machine_ed8864_idx",
        ),
        migrations.RenameIndex(
            model_name="machine",
            new_name="machine_section_etat_idx",
            old_name="sofemci_mac_section_383199_idx",
        ),
        migrations.RenameIndex(
            model_name="machine",
            new_name="machine_numero_idx",
            old_name="sofemci_mac_numero_e08442_idx",
        ),
        migrations.RenameIndex(
            model_name="machine",
            new_name="machine_type_idx",
            old_name="sofemci_mac_type_ma_afe02f_idx",
        ),
        migrations.RenameIndex(
            model_name="productionextrusion",
            new_name="prod_extrusion_date_zone_idx",
            old_name="sofemci_pro_date_pr_06d4a9_idx",
        ),
        migrations.RenameIndex(
            model_name="productionextrusion",
            new_name="prod_extrusion_valide_idx",
            old_name="sofemci_pro_valide_7a4664_idx",
        ),
        migrations.RenameIndex(
            model_name="productionimprimerie",
            new_name="prod_imprimerie_date_idx",
            old_name="sofemci_pro_date_pr_a0b081_idx",
        ),
        migrations.RenameIndex(
            model_name="productionimprimerie",
            new_name="prod_imprimerie_valide_idx",
            old_name="sofemci_pro_valide_133d45_idx",
        ),
        migrations.RenameIndex(
            model_name="productionrecyclage",
            new_name="prod_recyclage_date_equipe_idx",
            old_name="sofemci_pro_date_pr_d61d49_idx",
        ),
        migrations.RenameIndex(
            model_name="productionrecyclage",
            new_name="prod_recyclage_valide_idx",
            old_name="sofemci_pro_valide_67c84f_idx",
        ),
        migrations.RenameIndex(
            model_name="productionsoudure",
            new_name="prod_soudure_date_idx",
            old_name="sofemci_pro_date_pr_548dd5_idx",
        ),
        migrations.RenameIndex(
            model_name="productionsoudure",
            new_name="prod_soudure_valide_idx",
            old_name="sofemci_pro_valide_19dd92_idx",
        ),
        migrations.AlterField(
            model_name="alerteia",
            name="probabilite_panne",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Probabilité de panne (%)",
            ),
        ),
        migrations.AlterField(
            model_name="historiquemachine",
            name="cout_intervention",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Coût intervention (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="historiquemachine",
            name="duree_intervention",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Durée intervention (heures)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="capacite_horaire",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Capacité horaire (kg/h)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="consommation_electrique_kwh",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Consommation électrique (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="consommation_electrique_nominale",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Consommation nominale (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="duree_moyenne_reparation",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Durée moyenne réparation (heures)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="heures_depuis_derniere_maintenance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Heures depuis dernière maintenance",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="heures_fonctionnement_totales",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Heures fonctionnement totales",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="probabilite_panne_30_jours",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Probabilité panne (30 jours, %)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="probabilite_panne_7_jours",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Probabilité panne (7 jours, %)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="temperature_actuelle",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Température actuelle (°C)",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="temperature_nominale",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Température nominale (°C)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="dechets",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="matiere_premiere_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Matière première (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="nombre_bobines_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de bobines (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="nombre_machines_actives",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="nombre_machinistes",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machinistes",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="production_finis_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production finis (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="production_par_machine",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production par machine (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="production_semi_finis_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production semi-finis (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="rendement_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Rendement matière (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionextrusion",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="dechets",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="nombre_machines_actives",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="production_bobines_finies_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bobines finies (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="production_bobines_semi_finies_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bobines semi-finies (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionimprimerie",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="dechets",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="nombre_moulinex",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de moulinex",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="production_bache_noir_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Bâche noire produite (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="production_broyage_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production broyage (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="production_par_moulinex",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production par moulinex (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="taux_transformation_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Taux de transformation (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionrecyclage",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="dechets",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Déchets générés (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="nombre_machines_actives",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Nombre de machines actives",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_batta_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production BATTA (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_bobines_finies_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bobines finies (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_bretelles_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production bretelles (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_rema_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production REMA-Plastique (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="production_sac_emballage_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Production sac d'emballage imprimé (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="taux_dechet_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Taux de déchet (%)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="total_production_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production totale (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productionsoudure",
            name="total_production_specifique_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Production spécifique totale (kg)",
            ),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(fields=["cree_par"], name="alerte_cree_par_idx"),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(fields=["assigne_a"], name="alerte_assigne_a_idx"),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(fields=["priorite"], name="alerte_priorite_idx"),
        ),
        migrations.AddIndex(
            model_name="alerteia",
            index=models.Index(fields=["niveau"], name="alerte_ia_niveau_idx"),
        ),
        migrations.AddIndex(
            model_name="alerteia",
            index=models.Index(fields=["traite_par"], name="alerte_ia_traite_par_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["last_name", "first_name"], name="customuser_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipe",
            index=models.Index(fields=["nom"], name="equipe_nom_idx"),
        ),
        migrations.AddIndex(
            model_name="equipe",
            index=models.Index(fields=["est_active"], name="equipe_active_idx"),
        ),
        migrations.AddIndex(
            model_name="historiquemachine",
            index=models.Index(fields=["type_evenement"], name="historique_type_idx"),
        ),
        migrations.AddIndex(
            model_name="historiquemachine",
            index=models.Index(fields=["technicien"], name="historique_technicien_idx"),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(fields=["zone_extrusion"], name="machine_zone_idx"),
        ),
        migrations.AddIndex(
            model_name="machine",
            index=models.Index(fields=["etat"], name="machine_etat_idx"),
        ),
        migrations.AddIndex(
            model_name="productionextrusion",
            index=models.Index(
                fields=["date_creation"], name="prod_extrusion_creation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionextrusion",
            index=models.Index(fields=["equipe"], name="prod_extrusion_equipe_idx"),
        ),
        migrations.AddIndex(
            model_name="productionimprimerie",
            index=models.Index(
                fields=["date_creation"], name="prod_imprimerie_creation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionrecyclage",
            index=models.Index(
                fields=["date_creation"], name="prod_recyclage_creation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionsoudure",
            index=models.Index(
                fields=["date_creation"], name="prod_soudure_creation_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zoneextrusion",
            index=models.Index(fields=["numero"], name="zone_numero_idx"),
        ),
        migrations.AddIndex(
            model_name="zoneextrusion",
            index=models.Index(fields=["active"], name="zone_active_idx"),
        ),
        migrations.AddIndex(
            model_name="zoneextrusion",
            index=models.Index(fields=["chef_zone"], name="zone_chef_idx"),
        ),
    ]
