# Generated by Django 6.0 on 2026-01-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sofemci",
            "0011_rename_sofemci_ale_statut_81fc48_idx_alerte_statut_section_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="nom",
            field=models.CharField(
                choices=[
                    ("MATIN", "Équipe Du Matin"),
                    ("SOIR", "Équipe Du Soir"),
                    ("NUIT", "Équipe De Nuit"),
                ],
                max_length=20,
                verbose_name="Nom de l'équipe",
            ),
        ),
    ]
